# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9YNDYH4EWAW8xS3q0YamnZCKqW1HV6L
"""

import streamlit as st

# Title of the app
st.title("Personalized Greeting App")

# Input field for the user's name
name = st.text_input("Enter your name:")

# Button to submit the name
if st.button("Submit"):
    if name:
        st.success(f"Hello, {name}! Welcome to the app!")
    else:
        st.error("Please enter your name.")

# Sidebar with additional options
st.sidebar.header("Options")
st.sidebar.write("You can use this app to get a personalized greeting.")